// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvkkxzieoysiizpclgxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2a2t4emllb3lzaWl6cGNsZ3hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTY2MjEsImV4cCI6MjA2MTI3MjYyMX0.ezjCCdeP9Aq5IOBWUU4JcAWNdovzcdkLOZcJKt_-zSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);